ModuleExport size_t RegisterMETAImage(void)
{
  MagickInfo
    *entry;

  entry=SetMagickInfo("8BIM");
  entry->decoder=(DecodeImageHandler *) ReadMETAImage;
  entry->encoder=(EncodeImageHandler *) WriteMETAImage;
  entry->adjoin=MagickFalse;
  entry->stealth=MagickTrue;
  entry->seekable_stream=MagickTrue;
  entry->description=ConstantString("Photoshop resource format");
  entry->module=ConstantString("META");
  (void) RegisterMagickInfo(entry);
  entry=SetMagickInfo("8BIMTEXT");
  entry->decoder=(DecodeImageHandler *) ReadMETAImage;
  entry->encoder=(EncodeImageHandler *) WriteMETAImage;
  entry->adjoin=MagickFalse;
  entry->stealth=MagickTrue;
  entry->seekable_stream=MagickTrue;
  entry->description=ConstantString("Photoshop resource text format");
  entry->module=ConstantString("META");
  (void) RegisterMagickInfo(entry);
  entry=SetMagickInfo("8BIMWTEXT");
  entry->decoder=(DecodeImageHandler *) ReadMETAImage;
  entry->encoder=(EncodeImageHandler *) WriteMETAImage;
  entry->adjoin=MagickFalse;
  entry->stealth=MagickTrue;
  entry->seekable_stream=MagickTrue;
  entry->description=ConstantString("Photoshop resource wide text format");
  entry->module=ConstantString("META");
  (void) RegisterMagickInfo(entry);
  entry=SetMagickInfo("APP1");
  entry->decoder=(DecodeImageHandler *) ReadMETAImage;
  entry->encoder=(EncodeImageHandler *) WriteMETAImage;
  entry->adjoin=MagickFalse;
  entry->stealth=MagickTrue;
  entry->seekable_stream=MagickTrue;
  entry->description=ConstantString("Raw application information");
  entry->module=ConstantString("META");
  (void) RegisterMagickInfo(entry);
  entry=SetMagickInfo("APP1JPEG");
  entry->decoder=(DecodeImageHandler *) ReadMETAImage;
  entry->encoder=(EncodeImageHandler *) WriteMETAImage;
  entry->adjoin=MagickFalse;
  entry->stealth=MagickTrue;
  entry->seekable_stream=MagickTrue;
  entry->description=ConstantString("Raw JPEG binary data");
  entry->module=ConstantString("META");
  (void) RegisterMagickInfo(entry);
  entry=SetMagickInfo("EXIF");
  entry->decoder=(DecodeImageHandler *) ReadMETAImage;
  entry->encoder=(EncodeImageHandler *) WriteMETAImage;
  entry->adjoin=MagickFalse;
  entry->stealth=MagickTrue;
  entry->seekable_stream=MagickTrue;
  entry->description=ConstantString("Exif digital camera binary data");
  entry->module=ConstantString("META");
  (void) RegisterMagickInfo(entry);
  entry=SetMagickInfo("XMP");
  entry->decoder=(DecodeImageHandler *) ReadMETAImage;
  entry->encoder=(EncodeImageHandler *) WriteMETAImage;
  entry->adjoin=MagickFalse;
  entry->stealth=MagickTrue;
  entry->seekable_stream=MagickTrue;
  entry->description=ConstantString("Adobe XML metadata");
  entry->module=ConstantString("META");
  (void) RegisterMagickInfo(entry);
  entry=SetMagickInfo("ICM");
  entry->decoder=(DecodeImageHandler *) ReadMETAImage;
  entry->encoder=(EncodeImageHandler *) WriteMETAImage;
  entry->adjoin=MagickFalse;
  entry->stealth=MagickTrue;
  entry->seekable_stream=MagickTrue;
  entry->description=ConstantString("ICC Color Profile");
  entry->module=ConstantString("META");
  (void) RegisterMagickInfo(entry);
  entry=SetMagickInfo("ICC");
  entry->decoder=(DecodeImageHandler *) ReadMETAImage;
  entry->encoder=(EncodeImageHandler *) WriteMETAImage;
  entry->adjoin=MagickFalse;
  entry->stealth=MagickTrue;
  entry->seekable_stream=MagickTrue;
  entry->description=ConstantString("ICC Color Profile");
  entry->module=ConstantString("META");
  (void) RegisterMagickInfo(entry);
  entry=SetMagickInfo("IPTC");
  entry->decoder=(DecodeImageHandler *) ReadMETAImage;
  entry->encoder=(EncodeImageHandler *) WriteMETAImage;
  entry->adjoin=MagickFalse;
  entry->stealth=MagickTrue;
  entry->seekable_stream=MagickTrue;
  entry->description=ConstantString("IPTC Newsphoto");
  entry->module=ConstantString("META");
  (void) RegisterMagickInfo(entry);
  entry=SetMagickInfo("IPTCTEXT");
  entry->decoder=(DecodeImageHandler *) ReadMETAImage;
  entry->encoder=(EncodeImageHandler *) WriteMETAImage;
  entry->adjoin=MagickFalse;
  entry->stealth=MagickTrue;
  entry->seekable_stream=MagickTrue;
  entry->description=ConstantString("IPTC Newsphoto text format");
  entry->module=ConstantString("META");
  (void) RegisterMagickInfo(entry);
  entry=SetMagickInfo("IPTCWTEXT");
  entry->decoder=(DecodeImageHandler *) ReadMETAImage;
  entry->encoder=(EncodeImageHandler *) WriteMETAImage;
  entry->adjoin=MagickFalse;
  entry->stealth=MagickTrue;
  entry->seekable_stream=MagickTrue;
  entry->description=ConstantString("IPTC Newsphoto text format");
  entry->module=ConstantString("META");
  (void) RegisterMagickInfo(entry);
  return(MagickImageCoderSignature);
}